version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: beifong_redis
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  beifong_app:
    build: .
    container_name: beifong_server
    restart: always
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - REDIS_URL=redis://redis:6379/0
      - CLIENT_BUILD_PATH=/app/web/build
    volumes:
      - ./beifong/.env:/app/beifong/.env:ro
      - beifong_data:/app/beifong/databases
      - beifong_podcasts:/app/beifong/podcasts
      - beifong_browsers:/app/beifong/browsers
      - beifong_static:/app/beifong/static
      - ./web/build:/app/web/build:ro
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/api/podcasts"]
      interval: 60s
      timeout: 30s
      retries: 3
    working_dir: /app/beifong

  beifong_worker:
    build: .
    container_name: beifong_worker
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./beifong/.env:/app/beifong/.env:ro
      - beifong_data:/app/beifong/databases
      - beifong_podcasts:/app/beifong/podcasts
      - beifong_browsers:/app/beifong/browsers
      - beifong_static:/app/beifong/static
    depends_on:
      redis:
        condition: service_healthy
    command: python celery_worker.py
    working_dir: /app/beifong

  beifong_scheduler:
    build: .
    container_name: beifong_scheduler
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./beifong/.env:/app/beifong/.env:ro
      - beifong_data:/app/beifong/databases
      - beifong_podcasts:/app/beifong/podcasts
      - beifong_browsers:/app/beifong/browsers
      - beifong_static:/app/beifong/static
    depends_on:
      redis:
        condition: service_healthy
    command: python scheduler.py
    working_dir: /app/beifong

volumes:
  redis_data:
  beifong_data:
  beifong_podcasts:
  beifong_browsers:
  beifong_static: